[build] explicitly link with pthreads
This fixes the following error encountered with gcc 11.1.0:

/usr/bin/ld: ../libmbgl-core.a(thread.cpp.o): undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status