[linux] gcc-5
keep libstdc++-4.9-dev for clang builds because
error: debug information for auto is not yet supported

https://stackoverflow.com/questions/24617679/workaround-for-debug-symbol-error-with-auto-member-function