[core] prevent errors for impossible loops in template expansion
Without this gcc 10.2.0 complains about the loops condition never to be
true with the following error:

src/mbgl/style/expression/compound_expression.cpp: In instantiation of ‘mbgl::style::expression::EvaluationResult mbgl::style::expression::detail::Signature<R(const mbgl::style::expression::EvaluationContext&, Params ...)>::applyImpl(const mbgl::style::expression::EvaluationContext&, const Args&, std::index_sequence<I ...>) const [with long unsigned int ...I = {}; R = mbgl::style::expression::Result<bool>; Params = {}; mbgl::style::expression::detail::SignatureBase::Args = std::vector<std::unique_ptr<mbgl::style::expression::Expression> >; std::index_sequence<I ...> = std::integer_sequence<long unsigned int>]’:
src/mbgl/style/expression/compound_expression.cpp:154:25:   required from ‘mbgl::style::expression::EvaluationResult mbgl::style::expression::detail::Signature<R(const mbgl::style::expression::EvaluationContext&, Params ...)>::apply(const mbgl::style::expression::EvaluationContext&, const Args&) const [with R = mbgl::style::expression::Result<bool>; Params = {}; mbgl::style::expression::detail::SignatureBase::Args = std::vector<std::unique_ptr<mbgl::style::expression::Expression> >]’
src/mbgl/style/expression/compound_expression.cpp:153:22:   required from here
src/mbgl/style/expression/compound_expression.cpp:161:35: error: comparison of unsigned expression in ‘< 0’ is always false [-Werror=type-limits]
  161 |         for (std::size_t i = 0; i < sizeof...(Params); ++i) {
      |                                 ~~^~~~~~~~~~~~~~~~~~~